TI Recipe: Ensure each production component has at least one Datadog SLO
RoadieHQ/marketing-site pull request #1072
Opened 2023-07-25 17:24 UTC by JoaoMartins51

https://app.shortcut.com/larder/story/15890/write-ti-tutorial-ensure-each-production-component-has-at-least-one-datadog-slo

2023-07-26 08:54 UTC, dtuite requested changes

2023-07-26 08:54 UTC, dtuite commented on content/docs/tech-insights/track-datadog-slos/index.md
> +- Access to your system's components: Ensure you have the necessary permissions to access the components you want to track.
It's not totally clear to me what this means. Do I need access to the Backstage components, or the Datadog "services"? Maybe explain why we're going to need the access. That will make it more clear.

2023-07-26 08:54 UTC, dtuite commented on content/docs/tech-insights/track-datadog-slos/index.md
> +With Roadie’s Tech Insights feature, there’s an easier way. In this tutorial, we’re going to:
This is slightly different content than the "Prerequisites". I'd recommend splitting this out into it's own section called "What you'll learn"

2023-07-26 08:54 UTC, dtuite commented on content/docs/tech-insights/track-datadog-slos/index.md
> +2. You may need to wait some time for the data source to collect all SLOs and Monitors from Datadog. It must contact the Datadog APIs for each component which is captured by the already set filter.
We're missing a step here I think. Don't we need to teach the user how to set the annotations on some components so that this DS will work?

2023-07-31 12:08 UTC, jorgelainfiesta reviewed
Great tutorial! Left a few comments that can help improve clarity for the reader if they're not already familiar with Tech Insights.

2023-07-31 12:08 UTC, jorgelainfiesta commented on content/docs/tech-insights/track-datadog-slos/index.md
> +2. You may need to wait some time for the data source to collect all SLOs and Monitors from Datadog. It must contact the Datadog APIs for each component, which is captured by the already set filter.
Might be useful to add more details on what this filter is about (who sets it, when, can it be changed).

2023-07-31 12:08 UTC, jorgelainfiesta commented on content/docs/tech-insights/track-datadog-slos/index.md
> +This chart tells us:
You've been using "you" as a subject throughout most of the article. It's better not to change it to "us" now, but keep it all consistent. The case of "our data source" a bit before this paragraph is also confusing: does it refer to the data source usage you described just now or to Roadie's implementation

2023-07-31 12:08 UTC, jorgelainfiesta commented on content/docs/tech-insights/track-datadog-slos/index.md
> +In the next section, we will create a Check that can show a pass or fail result to app dev teams to tell them if they are missing any component that doesn’t have an SLO defined.
Considering re-phrasing this sentence, perhaps splitting it into two sentences? I'm not quite sure about what you want to say exactly

2023-07-31 12:08 UTC, jorgelainfiesta commented on content/docs/tech-insights/track-datadog-slos/index.md
> +Now that we can determine which components are using Dockerfiles, and we can extract the base image version from those files, let’s write a check to combine both of these properties.
When did Dockerfiles come into play?

2023-07-31 12:08 UTC, jorgelainfiesta commented on content/docs/tech-insights/track-datadog-slos/index.md
> +3. In the Conditions section, we’re going to create a condition that compares against the Datadog Slo facts retrieved from the data source.
I think the notion of a 'fact' is rather blurry as it wasn't introduced earlier. Might be useful to refer to the results of the Data Source as 'facts' in the previous section

2023-08-02 11:30 UTC, jorgelainfiesta approved these changes
Looks great, left some suggestions on formatting

2023-08-02 11:30 UTC, jorgelainfiesta commented on content/docs/tech-insights/track-datadog-slos/index.md
> +Set the hostname of your Datadog app.
```suggestion
1. Go to _Administration → Settings → Datadog_ and set the hostname of your Datadog app.
```

2023-08-02 11:30 UTC, jorgelainfiesta commented on content/docs/tech-insights/track-datadog-slos/index.md
> +
```suggestion
2. Go to _Administration → Settings → Secrets_  and set the `Datadog API Token` and `Datadog APP Token` in so your Roadie instance to contact your Datadog app.
```

2023-08-03 08:05 UTC, dtuite approved these changes

2023-08-03 08:06 UTC, merged