update - change github pull request page to meets new requirements
RoadieHQ/marketing-site pull request #25
Opened 2020-10-06 14:19 UTC by lewtakm

Update the Github pull request plugin page.

2020-10-06 15:41 UTC, iain-b submitted a review, later dismissed

2020-10-06 16:01 UTC, dtuite requested changes
This part doesn't look right. Shouldn't there be something inside `element={}`?

![Screenshot 2020-10-06 at 16 59 49](https://user-images.githubusercontent.com/562403/95226948-6f435e00-07f5-11eb-9a52-db0c71b3fbef.png)

Here's the preview link: https://deploy-preview-25--roadie.netlify.app/backstage/plugins/github-pull-requests

2020-10-07 07:59 UTC, lewtakm commented
> This part doesn't look right. Shouldn't there be something inside `element={}`?
> 
> ![Screenshot 2020-10-06 at 16 59 49](https://user-images.githubusercontent.com/562403/95226948-6f435e00-07f5-11eb-9a52-db0c71b3fbef.png)
> 
> Here's the preview link: https://deploy-preview-25--roadie.netlify.app/backstage/plugins/github-pull-requests

You are right, I forgot to encode one opening bracket and parser removed it from the code.

2020-10-07 13:00 UTC, dtuite approved these changes
Looks good!

2020-10-09 09:13 UTC, merged